trigger:
  - main

pool:
  name: Default

variables:
  vmImageName: 'ubuntu-latest'
  imageRepository: build-magick
  dockerFilePath: Dockerfile
  dockerRegistryServiceConnection: rayhaleblian.azurecr.io
  tag: latest

stages:
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build job
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build image
      inputs:
        command: build
        # repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        # containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
