# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

steps:

- task: ContainerBuild@0
  inputs:
    dockerRegistryServiceConnection: 'yoyodyne'
    repository: 'imagemagick'
    Dockerfile: 'Dockerfile'
