trigger:
  - main

pool:
  name: Default

variables:
  vmImageName: 'ubuntu-latest'
  imageRepository: build-magick
  dockerFilePath: Dockerfile
  dockerRegistryServiceConnection: rayhaleblian.azurecr.io
  tag: latest

steps:
- task: Docker@2
  displayName: Build image
  inputs:
    command: build
    # repository: $(imageRepository)
    dockerfile: $(dockerfilePath)
    # containerRegistry: $(dockerRegistryServiceConnection)
    tags: |
      $(tag)
